CREATE DATABASE database1;

CREATE TABLE IF NOT EXISTS employees
( id BIGINT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  position VARCHAR(128) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
);